apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: li6gejvcf-nodejs
  janus-idp.io/tekton: li6gejvcf-nodejs
  backstage.io/kubernetes-id: li6gejvcf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: li6gejvcf-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
