apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: li6gejvcf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: li6gejvcf-nodejs 
  name: li6gejvcf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: li6gejvcf-nodejs 
